server
{
    listen 8080;

    server_name localhost;

    root ./www;

    # the file it will be used in case of default. It's inside the folder docs
    index index.html;

    # max size of request body kept in memory
    client_body_buffer_size 4096;
    
    error_page 200 /error_pages/200.html;
    error_page 201 /error_pages/201.html;
    error_page 204 /error_pages/204.html;
    error_page 301 /error_pages/301.html;
    error_page 302 /error_pages/302.html;
    error_page 400 /error_pages/400.html;
    error_page 403 /error_pages/403.html;
    error_page 404 /error_pages/404.html;
    error_page 405 /error_pages/405.html;
    error_page 500 /error_pages/500.html;
    error_page 502 /error_pages/502.html;
    error_page 503 /error_pages/503.html;

    mime_types
    {
        text/html html htm;
        text/css css;
        application/javascript js;
        application/json json;
        image/png png;
        image/jpeg jpg jpeg;
        image/gif gif;
        image/x-icon ico;
        image/svg+xml svg;
        text/plain txt;
        application/pdf pdf;
        application/zip zip;
        application/xml xml;
        video/mp4 mp4;
        audio/mpeg mp3;
    }

    # block that specifies how to handle requests for a specific path or URL pattern
    location /
    {
        autoindex off;
        #uri checks for docs/. uri/ checks docs/index.html
        try_files $uri $uri/ =404;
        allowed_methods GET POST;
    }
    # static files dont need methods
    location /images/
    {
        root ./www;
        autoindex on;
    }

    location /test/
    {
        allowed_methods GET POST;
        root ./www;
        autoindex on;
    }

    location /fobidden/
    {
        return 403;
    }

    location /redir/
    {
        return 301 https://profile-v3.intra.42.fr/;
    }

    location /cgi-bin/
    {
        root ./www/cgi-bin;
        cgi_pass on;
        cgi_ext .php .py .sh;
        allowed_methods GET POST;
        autoindex off;
    }
}


