server
{
    listen 8080;
    server_name webserver;

    # folder that contains all the html, css, images etc, that the client will see when trying to access our server
    root docs;

    # the file it will be used in case of default. It's inside the folder docs
    index index.html;

    client_body_buffer_size 10000;

    # block that specifies how to handle requests for a specific path or URL pattern
    location /
    {
        allowed_methods GET POST DELETE;
    }
}
