server
{
	listen 8080;
	server_name localhost;

	root docs;
	# the file it will be used in case of default. It's inside the folder docs
	index index.html;

	# max size of request body kept in memory
	client_body_buffer_size 10000;

	mime_types
	{
		text/html html htm;
		text/css css;
		application/javascript js;
		application/json json;
		image/png png;
		image/jpeg jpg jpeg;
		image/gif gif;
		image/x-icon ico;
		image/svg+xml svg;
		text/plain txt;
		application/pdf pdf;
		application/zip zip;
		application/xml xml;
		video/mp4 mp4;
		audio/mpeg mp3;
	}

	# block that specifies how to handle requests for a specific path or URL pattern
	location /
	{
		#uri checks for docs/. uri/ checks docs/index.html
		try_files $uri $uri/ =404;
	}
	
	# static files dont need methods
	location /images/
	{
		root docs;
		autoindex off;
	}

	location /cgi-bin/
	{
		root docs;
		cgi_pass on;
		allowed_methods GET POST;
	}
}
